version: "3.4"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    hostname: nodeexplorer_server
    restart: always
    container_name: nodeexplorer_server_container
    command: npm start
    volumes:
      - ${NODEXPLORER_FOLDER:-./share}:/share
    networks:
      - net
  reverse-proxy:
    image: nginx
    restart: always
    container_name: nodeexplorer_nginx_container
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
#      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - server
    networks:
      - net
    ports:
      - ${PROXYPORT:-80}:80
#      - 443:443
networks:
  net:
    driver: bridge
